apiVersion: v1
kind: Service
metadata:
  labels:
    app: mvc-core-webapp
  name: mvc-core-webapp
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mvc-core-webapp
  sessionAffinity: None
  type: NodePort
